# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jh6lNz8kYCnpDcsR2IAEzPdHdccODRU3
"""

import pandas as pd

ism = [
    "Ali", "Vali", "Hasan", "Husan", "Gulnora",
    "Sarvar", "Zarina", "Dilshod", "Feruza", "Rustam"
]

familiya = [
    "Ahmedov", "Alimov", "Karimov", "Nasirov", "Rakhimova",
    "Saidov", "Komilova", "Usmonov", "Rustamova", "Ganiev"
]

yoshi = [
    25, 30, 22, 28, 35,
    19, 21, 29, 24, 31
]

print("Ism (First Names):")
display(ism)
print("\nFamiliya (Last Names):")
display(familiya)
print("\nYoshi (Ages):")
display(yoshi)

# Assuming the previously defined 'ism', 'familiya', and 'yoshi' lists are available.
# Let's identify the indices of typically female names.
# This is based on common Uzbek naming conventions and might not be exhaustive or 100% accurate.

female_indices = []
female_first_names = []
female_last_names = []
female_ages = []


for i in range(len(ism)):
    if ism[i] in ["Gulnora", "Zarina", "Feruza"]:
        female_indices.append(i)

for index in female_indices:
    female_first_names.append(ism[index])
    female_last_names.append(familiya[index])
    female_ages.append(yoshi[index])

print("Ayol ismlar (Female First Names):")
display(female_first_names)
print("\nAyol familiyalar (Female Last Names):")
display(female_last_names)
print("\nAyol yoshlari (Female Ages):")
display(female_ages)